# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Best Daily Podcast
email: contact@bestdailypodcast.xyz
description: "We have picked the best daily podcasts for you to listen.These audios will make your commute, gym session or morning routines more interesting!"
subtitle: ""
lang: en-us
author: carper
copyright: "&#xA9; 2022"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bestdailypodcast.xyz" # the base hostname & protocol for your site
twitter_username: 
github_username: 

permalink: /:year/:title.html

#Timezone
timezone: United States/New York

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

theme: jekyll-theme-minimal
